set nocompatible
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'Lokaltog/vim-powerline'
Bundle 'chriskempson/base16-vim'
Bundle 'christoomey/vim-tmux-navigator'
Bundle 'elixir-lang/vim-elixir'
Bundle 'gmarik/vundle'
Bundle 'guns/vim-clojure-static'
Bundle 'kien/ctrlp.vim'
Bundle 'kien/rainbow_parentheses.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'axskern/base16-vim-powerline'
Bundle 'tpope/vim-dispatch'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fireplace'
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-sleuth'
Bundle 'vim-scripts/paredit.vim'

set shell=/usr/local/bin/zsh
set number
set mouse=a
set ttymouse=xterm2
set hlsearch
set noshowmode
set nobackup
set nowritebackup
set noswapfile
set winwidth=20
set winminwidth=20
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

" Colors
set background=dark
colorscheme base16-default

" jk is the new escape.
inoremap jk <esc>

" Use comma as the leader key.
let mapleader=','
let maplocalleader='\'

" Swap semicolon and colon.
nnoremap ; :
nnoremap : ;

" Navigate wrapped lines better.
nnoremap j gj
nnoremap k gk

" Disable the arrow keys.
inoremap <esc> <nop>
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" %% to write the current directory in commands.
cnoremap %% <c-r>=expand('%:h').'/'<cr>

" Leader-S to sort the selected lines.
vnoremap <leader>s :sort<cr>

" CtrlP
let g:ctrlp_map = '<Space>'

" Powerline
let g:Powerline_symbols = 'fancy'
let g:Powerline_colorscheme = 'base16'
