export DOTFILES=$HOME/.dotfiles
export DOTFILES_BIN=$DOTFILES/bin
export DOTFILES_LIB=$DOTFILES/lib
export DOTFILES_FUNCTIONS=$DOTFILES_LIB/functions

fpath=($DOTFILES_FUNCTIONS $fpath)
autoload -U $DOTFILES_FUNCTIONS/*(:t)

source $DOTFILES_LIB/options.zsh
source $DOTFILES_LIB/history.zsh
source $DOTFILES_LIB/path.zsh
source $DOTFILES_LIB/aliases.zsh
source $DOTFILES_LIB/jumpdir.zsh
source $DOTFILES_LIB/editor.zsh
source $DOTFILES_LIB/rbenv.zsh
