#!/usr/local/bin/fish

for dest in $PWD/lib/*
  set basename (basename $dest)
  set src $HOME/.$basename

  if begin; test ! -h $src; or test $dest != (readlink $src); end
    if test -e $src
      read -p "echo \"Replace $src? (n) \"" answer

      if test $answer != "y"
        continue
      end
    end

    echo "$src -> $dest"
    rm -rf $src
    ln -s $dest $src
  end
end
