# env
export HOMEBREW="/usr/local"
export EDITOR=neovim
export PATH=$HOME/.dotfiles/bin:$PATH
export PAVLOV_HOME=$HOME/Pavlov
export CXXFLAGS="-I$HOMEBREW/include"
export LDFLAGS="-L$HOMEBREW/lib"
export PAGER=vimpager

# base16
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# prompt
source $HOME/.dotfiles/zsh/zsh-git-prompt.sh
export PROMPT='%B%c%b$(git_super_status) %F{magenta}%#%F{reset} '
