# env
export HOMEBREW="/usr/local"
export EDITOR=nvim
export PATH=$HOME/.dotfiles/bin:$PATH
export CXXFLAGS="-I$HOMEBREW/include"
export LDFLAGS="-L$HOMEBREW/lib"
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$CUDA_HOME:$CUDA_HOME/extras/CUPTI/lib"
export LD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"
# export PAGER=vimpager

# base16
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# prompt
source $HOME/.dotfiles/zsh/zsh-git-prompt.sh
export PROMPT='%B%~%b$(git_super_status) %F{magenta}%#%F{reset} '

# aliases
alias vim=nvim
alias v=nvim
alias gs='git status -sb'
alias gcob='git checkout -b'
alias gco='git checkout'
alias gc='git commit -av'
alias gb='git branch'
alias gp='git push'
alias l='exa'

# complete
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit

# kubectl
source <(kubectl completion zsh)

# go
export GOPATH="/usr/local/go"
export PATH="$GOPATH/bin:$PATH"

# rustup
source $HOME/.cargo/env

# jump
j() {
  cd ~/Cleargraph/"${1:-}"
}
compctl -/ -W ~/Cleargraph j

# find and replace in directory
replace-in-dir() {
  ag -l "$1" | xargs sed -i '' -e "s/$1/$2/g"
}

# history
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

# command + left/right
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line

# option + left/right
bindkey "^[^[[C" forward-word
bindkey "^[^[[D" backward-word

# option + delete
bindkey "^[d" backward-kill-word

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/google-cloud-sdk/path.zsh.inc' ]; then source '/usr/local/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/google-cloud-sdk/completion.zsh.inc' ]; then source '/usr/local/google-cloud-sdk/completion.zsh.inc'; fi

# fzf & ripgrep
export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --follow --glob "!.git/*"'

# ruby
export PATH=/usr/local/opt/ruby/bin:$PATH

# Cleargraph Mono ;)
if [[ -d ~/Cleargraph/mono/bin ]]; then export PATH=~/Cleargraph/mono/bin:$PATH; fi

export PATH="$HOME/.yarn/bin:$PATH"
